fix version problems
node-casbin/mongoose-adapter pull request #52
Opened 2022-01-28 10:25 UTC by fabian4

Related issue: https://github.com/node-casbin/mongoose-adapter/issues/51

2022-01-28 12:10 UTC, hsluoyz requested changes

2022-01-28 12:10 UTC, hsluoyz commented on yarn.lock
> +  "resolved" "https://registry.npmmirror.com/@babel/code-frame/download/@babel/code-frame-7.12.11.tgz"
Plz still use: registry.npmjs.org

2022-01-28 12:10 UTC, hsluoyz commented
@fabian4 plz also fix:

![image](https://user-images.githubusercontent.com/3787410/151544746-69c332fa-9f09-48e7-906c-96a8d033eff1.png)

2022-01-28 12:17 UTC, hsluoyz commented
@fabian4 the CI failed:

![image](https://user-images.githubusercontent.com/3787410/151545580-6e72c880-17f1-44cf-a1aa-fb336b5d0543.png)

2022-01-28 15:21 UTC, hsluoyz commented
@sapcik plz review

2022-01-28 15:22 UTC, hsluoyz approved these changes

2022-01-29 07:13 UTC, nodece approved these changes

2022-01-29 07:34 UTC, merged